spring:
  datasource:
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8
    username: root
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 30000
      maximum-pool-size: 15
logging:
  level:
    com:
      dao: debug


#mybatis:
#  configuration:
#  mapper-locations: classpath:mybatis/*/*.xml
#  type-aliases-package: com.entity

mybatis-plus:
  check-config-location: true
  type-aliases-package: com.entity
  mapper-locations: classpath:mybatis/*/*.xml
  config-location: classpath:mybtais-config.xml
  type-handlers-package: com.typehandle
